server:
  servlet:
    context-path: /api

spring:
  application:
    name: innowise-auth-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/innowise_auth_service_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

jwt:
  access:
    key: ${JWT_ACCESS_KEY}
    expiration-ms: ${JWT_ACCESS_EXPIRATION:900000} # 15 minutes
  refresh:
    key: ${JWT_REFRESH_KEY}
    expiration-ms: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

integration:
  user-service-url: ${USER_SERVICE_URL}