services:
  user-service-app:
    build: ./user-service
    ports:
      - "${USER_SERVICE_APP_PORT}:8080"
    depends_on:
      - user-service-db
      - user-service-redis
    environment:
      SPRING_PROFILES_ACTIVE: ${USER_SERVICE_SPRING_PROFILES_ACTIVE}
      DB_URL: ${USER_SERVICE_DB_URL}
      DB_USERNAME: ${USER_SERVICE_DB_USERNAME}
      DB_PASSWORD: ${USER_SERVICE_DB_PASSWORD}

  user-service-db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "${USER_SERVICE_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${USER_SERVICE_DB_NAME}
      POSTGRES_USER: ${USER_SERVICE_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service-redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "${USER_SERVICE_REDIS_PORT}:6379"

  auth-service-app:
    build: ./auth-service
    ports:
      - "${AUTH_SERVICE_APP_PORT}:8080"
    depends_on:
      - auth-service-db
    environment:
      DB_URL: ${AUTH_SERVICE_DB_URL}
      DB_USERNAME: ${AUTH_SERVICE_DB_USERNAME}
      DB_PASSWORD: ${AUTH_SERVICE_DB_PASSWORD}
      JWT_ACCESS_KEY: ${JWT_ACCESS_KEY}
      JWT_REFRESH_KEY: ${JWT_REFRESH_KEY}
      USER_SERVICE_URL: ${USER_SERVICE_URL}

  auth-service-db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "${AUTH_SERVICE_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${AUTH_SERVICE_DB_NAME}
      POSTGRES_USER: ${AUTH_SERVICE_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_DB_PASSWORD}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  order-service-app:
    build: ./order-service
    ports:
      - "${ORDER_SERVICE_APP_PORT}:8080"
    depends_on:
      - order-service-db
      - user-service-app
      - kafka
    environment:
      DB_URL: ${ORDER_SERVICE_DB_URL}
      DB_USERNAME: ${ORDER_SERVICE_DB_USERNAME}
      DB_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}

  order-service-db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "${ORDER_SERVICE_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${ORDER_SERVICE_DB_NAME}
      POSTGRES_USER: ${ORDER_SERVICE_DB_USERNAME}
      POSTGRES_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD}
    volumes:
      - order_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-service-app:
    build: ./payment-service
    ports:
      - "${PAYMENT_SERVICE_APP_PORT}:8080"
    depends_on:
      kafka:
        condition: service_started
      payment-service-db:
        condition: service_healthy
    environment:
      RANDOM_NUMBER_API_URL: ${PAYMENT_SERVICE_RANDOM_NUMBER_API_URL}
      SPRING_DATA_MONGODB_URI: ${PAYMENT_SERVICE_DB_URL}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}

  payment-service-db:
    image: mongo:6.0
    restart: always
    ports:
      - "${PAYMENT_SERVICE_DB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PAYMENT_SERVICE_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PAYMENT_SERVICE_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${PAYMENT_SERVICE_DB_NAME}
    volumes:
      - payment_db_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    restart: always
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api-gateway-service-app:
    build: ./api-gateway
    ports:
      - "${API_GATEWAY_SERVICE_APP_PORT}:8080"
    environment:
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      ORDER_SERVICE_URL: ${ORDER_SERVICE_URL}
      PAYMENT_SERVICE_URL: ${PAYMENT_SERVICE_URL}
      JWT_ACCESS_KEY: ${JWT_ACCESS_KEY}
      JWT_REFRESH_KEY: ${JWT_REFRESH_KEY}
    depends_on:
      - user-service-app
      - auth-service-app
      - order-service-app
      - payment-service-app

volumes:
  user_db_data:
  auth_db_data:
  order_db_data:
  payment_db_data: