spring:
  application:
    name: innowise-api-gateway

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: Authentication
          routes:
            - id: user-service-route
              uri: ${USER_SERVICE_URL}
              predicates:
                - Path=/api/users/**

            - id: auth-service-route
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/api/auth/**

            - id: order-service-route
              uri: ${ORDER_SERVICE_URL}
              predicates:
                - Path=/api/orders/**

            - id: payment-service-route
              uri: ${PAYMENT_SERVICE_URL}
              predicates:
                - Path=/api/payments/**
              filters:
                - Authentication

jwt:
  access-key: ${JWT_ACCESS_KEY}
  refresh-key: ${JWT_REFRESH_KEY}
