apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/api/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: user-app
          image: user-service-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: TEMPO_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TEMPO_URL
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_SERVICE_SPRING_PROFILES_ACTIVE
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USER_SERVICE_DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_SERVICE_DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USER_SERVICE_DB_PASSWORD

          livenessProbe:
            httpGet:
              path: /api/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-app
spec:
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080