apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/api/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: gateway-app
          image: api-gateway-service-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: TEMPO_URL
              value: "http://tempo:4317"
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_SERVICE_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PAYMENT_SERVICE_URL
            - name: JWT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_ACCESS_KEY
            - name: JWT_REFRESH_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_REFRESH_KEY
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service-app
spec:
  selector:
    app: gateway-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080