spring:
  application:
    name: user-app

user:
  card:
    max-limit: 5

cache:
  ttl:
    user: 10m
    card: 10m
    cards: 5m

jwt:
  access:
    key: ${JWT_ACCESS_KEY:6aec213d794e0cbd15a0bd961b21b2e6d74376ad897f8423939278479b20c7fb}
    expiration-ms: ${JWT_ACCESS_EXPIRATION:900000}
  refresh:
    key: ${JWT_REFRESH_KEY:cde001b26cb22a86028a441d3c5b600a935a4606cd4b70aa03e5f679b5f2023d}
    expiration-ms: ${JWT_REFRESH_EXPIRATION:604800000}

server:
  servlet:
    context-path: /api

management:
  zipkin:
    tracing:
      endpoint: ${TEMPO_URL:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, tracing
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3

  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
