apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  USER_SERVICE_SPRING_PROFILES_ACTIVE: "docker"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  USER_SERVICE_URL: "http://user-service-app:8080"
  AUTH_SERVICE_URL: "http://auth-service-app:8080"
  ORDER_SERVICE_URL: "http://order-service-app:8080"
  PAYMENT_SERVICE_URL: "http://payment-service-app:8080"

  USER_SERVICE_DB_NAME: "user_db"
  USER_SERVICE_DB_USERNAME: "postgres"
  AUTH_SERVICE_DB_NAME: "auth_db"
  AUTH_SERVICE_DB_USERNAME: "postgres"
  ORDER_SERVICE_DB_NAME: "order_db"
  ORDER_SERVICE_DB_USERNAME: "postgres"
  PAYMENT_SERVICE_DB_NAME: "payment_db"
  PAYMENT_SERVICE_DB_USERNAME: "root"

  PAYMENT_SERVICE_RANDOM_NUMBER_API_URL: "https://csrng.net/csrng/csrng.php?min=1&max=100"

  TEMPO_URL: "http://tempo:9411/api/v2/spans"

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  JWT_ACCESS_KEY: "6aec213d794e0cbd15a0bd961b21b2e6d74376ad897f8423939278479b20c7fb"
  JWT_REFRESH_KEY: "cde001b26cb22a86028a441d3c5b600a935a4606cd4b70aa03e5f679b5f2023d"

  USER_SERVICE_DB_PASSWORD: "postgres"
  AUTH_SERVICE_DB_PASSWORD: "postgres"
  ORDER_SERVICE_DB_PASSWORD: "postgres"
  PAYMENT_SERVICE_DB_PASSWORD: "secret"

  USER_SERVICE_DB_URL: "jdbc:postgresql://user-service-db:5432/user_db"
  AUTH_SERVICE_DB_URL: "jdbc:postgresql://auth-service-db:5432/auth_db"
  ORDER_SERVICE_DB_URL: "jdbc:postgresql://order-service-db:5432/order_db"
  PAYMENT_SERVICE_DB_URL: "mongodb://root:secret@payment-service-db:27017/payment_db?authSource=admin"