spring:
  application:
    name: innowise-order-service

  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/order_service_db}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: order-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: "com.innowise.orderservice.kafka.event.PaymentEvent"
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"

resilience4j:
  circuitbreaker:
    instances:
      userService:
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true

server:
  servlet:
    context-path: /api

integration:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8080}